name: PadelNative
options:
  deploymentTarget:
    iOS: 17.0
configs:
  Debug: debug
  Release: release
targets:
  PadelNative:
    type: application
    platform: iOS
    sources:
      - PadelNative
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.padelnative
        PRODUCT_NAME: PadelNative
        SWIFT_VERSION: 5.0
        # NOTE for non-coders: this tells Xcode to create the app's Info.plist file automatically during build.
        # Without it, Xcode can't package the app and code signing fails.
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_CFBundleDisplayName: Padel Native
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.sports
        INFOPLIST_KEY_SUPABASE_URL: $(SUPABASE_URL)
        INFOPLIST_KEY_SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        # NOTE for non-coders: these optional values let the app show update prompts even
        # when server-config lookup is unavailable.
        INFOPLIST_KEY_MINIMUM_SUPPORTED_VERSION: 1.0.0
        INFOPLIST_KEY_LATEST_AVAILABLE_VERSION: 1.0.0
        INFOPLIST_KEY_APP_STORE_URL: https://apps.apple.com/app/id0000000000
        # NOTE for non-coders: this key creates a default launch screen without additional storyboard files.
        INFOPLIST_KEY_UILaunchScreen_Generation: true
    configFiles:
      Debug: PadelNative/Config/AppSecrets.xcconfig
      Release: PadelNative/Config/AppSecrets.xcconfig

  PadelNativeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PadelNativeTests
    dependencies:
      - target: PadelNative
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.padelnative.tests
        PRODUCT_NAME: PadelNativeTests
        SWIFT_VERSION: 5.0
