name: PadelNative
options:
  deploymentTarget:
    iOS: 17.0
configs:
  Debug: debug
  Release: release
targets:
  PadelNative:
    type: application
    platform: iOS
    entitlements:
      path: PadelNative/PadelNative.entitlements
      # NOTE for non-coders: this stays empty for local/dev builds.
      # Personal Apple teams cannot sign the "Associated Domains" capability.
      properties: {}
    sources:
      - PadelNative
    settings:
      base:
        # NOTE for non-coders: this must be globally unique on Apple systems.
        # Replace with your own identifier if your org/team naming differs.
        PRODUCT_BUNDLE_IDENTIFIER: se.robban.padelnative
        # NOTE for non-coders: this must exactly match the production App Store Connect Bundle ID or installs/links can break.
        PRODUCT_NAME: PadelNative
        SWIFT_VERSION: 5.0
        # NOTE for non-coders: this tells Xcode to create the app's Info.plist file automatically during build.
        # Without it, Xcode can't package the app and code signing fails.
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        # NOTE: This controls the home-screen app label users see under the icon.
        INFOPLIST_KEY_CFBundleDisplayName: Grabbarnas Paddel app
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.sports
        INFOPLIST_KEY_SUPABASE_URL: $(SUPABASE_URL)
        INFOPLIST_KEY_SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        # NOTE for non-coders: iOS will hard-crash at launch if Face ID is used
        # without this exact permission text being present in the app's Info.plist.
        INFOPLIST_KEY_NSFaceIDUsageDescription: Face ID används för att låsa upp appen snabbare och säkert.
        # NOTE for non-coders: these optional values let the app show update prompts even
        # when server-config lookup is unavailable.
        INFOPLIST_KEY_MINIMUM_SUPPORTED_VERSION: 1.0.0
        INFOPLIST_KEY_LATEST_AVAILABLE_VERSION: 1.0.0
        INFOPLIST_KEY_APP_STORE_URL: https://apps.apple.com/app/idAPP_STORE_ID
        # NOTE for non-coders: replace idAPP_STORE_ID with your app's real App Store numeric ID from App Store Connect.
        # NOTE for non-coders: this key creates a default launch screen without additional storyboard files.
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        # NOTE for non-coders: this points Xcode to the entitlements file where Associated Domains is stored.
        CODE_SIGN_ENTITLEMENTS: PadelNative/PadelNative.entitlements
    configFiles:
      Debug: PadelNative/Config/AppSecrets.xcconfig
      Release: PadelNative/Config/AppSecrets.xcconfig

  PadelNativeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PadelNativeTests
    dependencies:
      - target: PadelNative
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.padelnative.tests
        PRODUCT_NAME: PadelNativeTests
        SWIFT_VERSION: 5.0


  PadelNativeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PadelNativeUITests
    dependencies:
      - target: PadelNative
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.padelnative.uitests
        PRODUCT_NAME: PadelNativeUITests
        SWIFT_VERSION: 5.0
