openapi: 3.1.0
info:
  title: Padel Contract
  version: 1.0.0
  description: >-
    Shared backend contract used by web data services and iOS native services.
servers:
  - url: https://example.supabase.co
paths:
  /auth/v1/token:
    post:
      summary: Sign in or refresh a session.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/AuthPasswordRequest'
                - $ref: '#/components/schemas/AuthRefreshRequest'
      responses:
        '200':
          description: Active auth session.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSessionResponse'
  /rest/v1/availability_votes:
    post:
      summary: Submit a vote for one day in a schedule poll.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleVoteRequest'
      responses:
        '201':
          description: Vote persisted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleVoteResponse'
  /rest/v1/matches:
    post:
      summary: Create a match entry in either 1v1 or 2v2 mode.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchCreateRequest'
      responses:
        '201':
          description: Match created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchCreateResponse'
components:
  schemas:
    MatchMode:
      type: string
      enum: [1v1, 2v2]
    AuthPasswordRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
    AuthRefreshRequest:
      type: object
      required: [refresh_token]
      properties:
        refresh_token:
          type: string
    AuthSessionResponse:
      type: object
      required: [access_token, refresh_token, expires_at, user]
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_at:
          type: number
        user:
          type: object
          required: [id]
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email
              nullable: true
    ScheduleVoteRequest:
      type: object
      required: [poll_day_id, profile_id, slot_preferences]
      properties:
        poll_day_id:
          type: string
          format: uuid
        profile_id:
          type: string
          format: uuid
        slot_preferences:
          type: array
          minItems: 1
          items:
            type: string
            enum: [morning, day, evening]
    ScheduleVoteResponse:
      type: object
      required: [id, poll_day_id, profile_id, slot_preferences, created_at]
      properties:
        id:
          type: string
          format: uuid
        poll_day_id:
          type: string
          format: uuid
        profile_id:
          type: string
          format: uuid
        slot_preferences:
          type: array
          items:
            type: string
            enum: [morning, day, evening]
        created_at:
          type: string
          format: date-time
    MatchCreateRequest:
      type: object
      required:
        - team1
        - team2
        - team1_sets
        - team2_sets
        - created_by
        - match_mode
      properties:
        team1:
          type: array
          minItems: 1
          maxItems: 2
          items:
            type: string
            minLength: 1
            maxLength: 50
        team2:
          type: array
          minItems: 1
          maxItems: 2
          items:
            type: string
            minLength: 1
            maxLength: 50
        team1_ids:
          type: array
          items:
            type: string
            format: uuid
            nullable: true
        team2_ids:
          type: array
          items:
            type: string
            format: uuid
            nullable: true
        team1_sets:
          type: integer
          minimum: 0
        team2_sets:
          type: integer
          minimum: 0
        created_by:
          type: string
          format: uuid
        source_tournament_id:
          type: string
          format: uuid
          nullable: true
        match_mode:
          $ref: '#/components/schemas/MatchMode'
    MatchCreateResponse:
      type: object
      required: [id, created_at]
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
